//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLivros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exemplar
    {
        public Exemplar()
        {
            this.Historico = new HashSet<Historico>();
        }
    
        public long id { get; set; }
        public long idTitulo { get; set; }
        public string editora { get; set; }
        public string edicao { get; set; }
        public long idIniciante { get; set; }
    
        public virtual Titulo Titulo { get; set; }
        public virtual ICollection<Historico> Historico { get; set; }
    }
}
