//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLivros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historico
    {
        public long id { get; set; }
        public long idLeitor { get; set; }
        public long idExemplar { get; set; }
    
        public virtual Exemplar Exemplar { get; set; }
        public virtual Leitor Leitor { get; set; }
    }
}
