//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLivros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leitor
    {
        public Leitor()
        {
            this.Historico = new HashSet<Historico>();
        }
    
        public long id { get; set; }
        public string nome { get; set; }
        public Nullable<int> idade { get; set; }
        public string estado { get; set; }
        public string cidade { get; set; }
        public string bairro { get; set; }
        public string email { get; set; }
        public string telefone { get; set; }
        public string senha { get; set; }
    
        public virtual ICollection<Historico> Historico { get; set; }
    }
}
