//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLivros.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLivrosEntities : DbContext
    {
        public QLivrosEntities()
            : base("name=QLivrosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TabBairro> TabBairro { get; set; }
        public DbSet<TabCidade> TabCidade { get; set; }
        public DbSet<TabEstado> TabEstado { get; set; }
        public DbSet<TabExemplar> TabExemplar { get; set; }
        public DbSet<TabHistorico> TabHistorico { get; set; }
        public DbSet<TabLeitor> TabLeitor { get; set; }
        public DbSet<TabLog> TabLog { get; set; }
        public DbSet<TabLogradouroEnd> TabLogradouroEnd { get; set; }
        public DbSet<TabMensagem> TabMensagem { get; set; }
        public DbSet<TabResenha> TabResenha { get; set; }
        public DbSet<TabSalaChat> TabSalaChat { get; set; }
        public DbSet<TabTitulo> TabTitulo { get; set; }
    }
}
