//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLivros.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLivrosEntities : DbContext
    {
        public QLivrosEntities()
            : base("name=QLivrosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Exemplar> Exemplar { get; set; }
        public DbSet<Historico> Historico { get; set; }
        public DbSet<Leitor> Leitor { get; set; }
        public DbSet<Titulo> Titulo { get; set; }
    }
}
