//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLivros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabBairro
    {
        public TabBairro()
        {
            this.TabLogradouroEnd = new HashSet<TabLogradouroEnd>();
        }
    
        public int idBairro { get; set; }
        public string nmBairro { get; set; }
        public int fkIdCidade { get; set; }
    
        public virtual TabCidade TabCidade { get; set; }
        public virtual ICollection<TabLogradouroEnd> TabLogradouroEnd { get; set; }
    }
}
