//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLivros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabCidade
    {
        public TabCidade()
        {
            this.TabBairro = new HashSet<TabBairro>();
        }
    
        public int idCidade { get; set; }
        public string nmCidade { get; set; }
        public int fkIdEstado { get; set; }
    
        public virtual ICollection<TabBairro> TabBairro { get; set; }
        public virtual TabEstado TabEstado { get; set; }
    }
}
