//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLivros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabEstado
    {
        public TabEstado()
        {
            this.TabCidade = new HashSet<TabCidade>();
        }
    
        public int idEstado { get; set; }
        public string nmEstado { get; set; }
    
        public virtual ICollection<TabCidade> TabCidade { get; set; }
    }
}
