//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLivros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabHistorico
    {
        public int idHistorico { get; set; }
        public System.DateTime dtHistorico { get; set; }
        public Nullable<int> dsStatus { get; set; }
        public Nullable<int> idReceptor { get; set; }
        public int fkIdExemplar { get; set; }
        public int fkIdLeitor { get; set; }
    
        public virtual TabExemplar TabExemplar { get; set; }
        public virtual TabLeitor TabLeitor { get; set; }
    }
}
