//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLivros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabLeitor
    {
        public TabLeitor()
        {
            this.TabHistorico = new HashSet<TabHistorico>();
            this.TabLog = new HashSet<TabLog>();
            this.TabResenha = new HashSet<TabResenha>();
            this.TabSalaChat = new HashSet<TabSalaChat>();
            this.TabSalaChat1 = new HashSet<TabSalaChat>();
        }
    
        public int idLeitor { get; set; }
        public string dsEmail { get; set; }
        public string dsLogin { get; set; }
        public string dsSenha { get; set; }
        public string nmLeitor { get; set; }
        public string dsSexo { get; set; }
        public System.DateTime dtNasc { get; set; }
        public string numCel { get; set; }
        public string dsRgLeitor { get; set; }
        public int noEnd { get; set; }
        public string dsComplementoEnd { get; set; }
        public string dsReferenciaEnd { get; set; }
        public string imFoto { get; set; }
        public int fkIdCepEnd { get; set; }
        public int dsStatus { get; set; }
    
        public virtual ICollection<TabHistorico> TabHistorico { get; set; }
        public virtual TabLogradouroEnd TabLogradouroEnd { get; set; }
        public virtual ICollection<TabLog> TabLog { get; set; }
        public virtual ICollection<TabResenha> TabResenha { get; set; }
        public virtual ICollection<TabSalaChat> TabSalaChat { get; set; }
        public virtual ICollection<TabSalaChat> TabSalaChat1 { get; set; }
    }
}
