//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLivros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabLogradouroEnd
    {
        public TabLogradouroEnd()
        {
            this.TabLeitor = new HashSet<TabLeitor>();
        }
    
        public int idCepEnd { get; set; }
        public string nmLogradouro { get; set; }
        public int fkIdBairro { get; set; }
    
        public virtual TabBairro TabBairro { get; set; }
        public virtual ICollection<TabLeitor> TabLeitor { get; set; }
    }
}
