//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLivros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabMensagem
    {
        public int idMensagem { get; set; }
        public string dsMensagem { get; set; }
        public int fkIdLeitor2 { get; set; }
        public int fkIdLeitor1 { get; set; }
        public int fkIdSala { get; set; }
        public System.DateTime dtMensagem { get; set; }
    
        public virtual TabSalaChat TabSalaChat { get; set; }
    }
}
