//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLivros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabSalaChat
    {
        public TabSalaChat()
        {
            this.TabMensagem = new HashSet<TabMensagem>();
        }
    
        public int idSala { get; set; }
        public int fkIdLeitor { get; set; }
        public int fkIdLeitor2 { get; set; }
    
        public virtual TabLeitor TabLeitor { get; set; }
        public virtual TabLeitor TabLeitor1 { get; set; }
        public virtual ICollection<TabMensagem> TabMensagem { get; set; }
    }
}
